name: appauth
description: "fetch a GitHub app auth token"
inputs:
  app_id:
    description: "ID of the GitHub App."
    required: true
  private_key:
    description: "Bot private key (PEM)"
    required: true
outputs:
  token:
    description: installation token for the GitHub App on the current repository.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: unlock
  color: gray-dark