name: update

on:
  workflow_dispatch:
  push:
    paths:
      - renovate.js
      - .github/workflows/update.yml
  schedule:
    - cron: "19 */3 * * *"
jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2
      - uses: ./.github/actions/appauth
        id: generate-token
        with:
          app_id: ${{ secrets.AUTH_FOR_GITHUB_APP_ID }}
          private_key: ${{ secrets.AUTH_FOR_GITHUB_PRIVATE_KEY }}
      - name: renovate
        uses: docker://renovate/renovate:24.16.6@sha256:ecc53c4a2e3530237d7197dd123646086e29f36b38b695b7f22f1fb35d949ce3
        env:
          RENOVATE_REPOSITORIES: kindlyops/enlist-mobile
          RENOVATE_TOKEN: x-access-token:${{ steps.generate-token.outputs.token }}
          RENOVATE_USERNAME: kindlymachine[bot]
          RENOVATE_ONBOARDING: true
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
          RENOVATE_TRUSTLEVEL: high
