name: update

on:
  workflow_dispatch:
  push:
    paths:
      - renovate.js
      - .github/workflows/update.yml
  schedule:
    - cron: "19 */3 * * *"
jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2
      - uses: ./.github/actions/appauth
        id: generate-token
        with:
          app_id: ${{ secrets.AUTH_FOR_GITHUB_APP_ID }}
          private_key: ${{ secrets.AUTH_FOR_GITHUB_PRIVATE_KEY }}
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:ad24338d5640b1d7561111b2fdd1406123f941d24a06f3589326038cbb4661fa
        env:
          RENOVATE_REPOSITORIES: kindlyops/enlist-mobile
          RENOVATE_TOKEN: x-access-token:${{ steps.generate-token.outputs.token }}
          RENOVATE_GITAUTHOR: "Renovate Bot <bot@renovate.com>"
          RENOVATE_USERNAME: renovatebot
          RENOVATE_ONBOARDING: true
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
          RENOVATE_TRUSTLEVEL: high
